### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by bendiknesbo** [auth0-extensions/canirequire#372]
The API that https://auth0-extensions.github.io/canirequire/ is calling is broken, and responds with HTTP Status 400.

Request URL: https://auth0-internal.us.webtask.io/canirequire
Status Code: 400 Bad Request
Response body:
```json
{
    "code": 400,
    "message": "Compilation failed: Cannot find module '/data/_verquire/_node18/packages.json'\nRequire stack:\n- /data/io/node18/d9e009b6-63fb-44a7-bb8d-984d2fdf1a11/webtask.js",
    "error": "Cannot find module '/data/_verquire/_node18/packages.json'\nRequire stack:\n- /data/io/node18/d9e009b6-63fb-44a7-bb8d-984d2fdf1a11/webtask.js",
    "stack": "Error: Cannot find module '/data/_verquire/_node18/packages.json'\nRequire stack:\n- /data/io/node18/d9e009b6-63fb-44a7-bb8d-984d2fdf1a11/webtask.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n    at _resolveFilenameInDir (/data/sandbox/lib/module.js:49:19)\n    at WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:215:12)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:199:39)\n    at require (/data/sandbox/lib/module.js:265:17)\n    at Object.<anonymous> (/data/io/node18/d9e009b6-63fb-44a7-bb8d-984d2fdf1a11/webtask.js:25:18)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:192:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:135:24)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:144:12)\n    at /data/sandbox/lib/compiler.js:294:11"
}
```

**Comment by joshbetz** [comment]
Thanks for the report. This has been fixed.
